### ISSUE TITLE
The splitter will move to the right when the mouse is moving over

### ISSUE THREAD

**Issue by fz0000** [jsleroy/compare-plugin#100]
### Steps:

1. Install NPP.
2. Install Compare plugin via Plugins Admin.
3. Open/New 2 files.
4. Drag to adjust the width of the Compare NavBar.
5. Move the mouse over the splitter.

### Expected:

Nothing happens.

### Actual: 

The splitter will move to the right. See the video below for details:
![compare](https://user-images.githubusercontent.com/5061311/59188736-f3a6b200-8baa-11e9-8475-ae1ab6ce2094.gif)

### Additional info:

1. This issue will **not** occur any more after any other mouse action (e.g. Click in the edit pane).
2. This issue will occur again if adjust the width of the Compare NavBar again.

### Debug Info

Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : D:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppXmlTreeviewPlugin.dll SQLinFormNpp64.dll XMLTools.dll 

---
In fact the issue occurs from a long time ago. And it seems that it's still not completely resolved on the latest version. So I just submit it here. Hope anyone can help to fix it.
By the way, there are 2 project links in the about dialog. If I submit to the wrong project please let me know. 😂

Thanks in advance!

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5554

Please open any other Compare issues in Pavel Nedev's repo.
