### ISSUE TITLE
编译好的完整包插件下载地址，解压到plugins目录可用

### ISSUE THREAD

**Issue by 1265578519** [jsleroy/compare-plugin#118]
C:\Program Files (x86)\Notepad++\plugins

[ComparePlugin.zip](https://github.com/jsleroy/compare-plugin/files/5979899/ComparePlugin.zip)

**Comment by TSaltedfishKing** [comment]
谢谢

**Comment by wxzvim** [comment]
> C:\Program Files (x86)\Notepad++\plugins
> 
> [ComparePlugin.zip](https://github.com/jsleroy/compare-plugin/files/5979899/ComparePlugin.zip)
这是32位的呀，，64位的notepad++载入不了
