### ISSUE TITLE
2.0.2 crashing Notepad++ (8.2.1 64-bit) on Compare Files

### ISSUE THREAD

**Issue by jcstevensri** [jsleroy/compare-plugin#124]
Notepad++ (8.2.1 64-bit) on Windows 10 Pro (21H2 OS Build 19044.1526) 

Notepad++ updated my ComparePlugin version from 2.0.1 (working) to 2.0.2 (crashing).
I select the first file using Ctrl+Alt+1.
When I select the file for comparison using Ctrl+Alt+C, I get a progress bar for a few seconds, then Notepad++ crashes.

The only way I could find to fix this was to close Notepad++ and swap the ComparePlugin.dll v2.0.2 with the v2.0.1 dll.

**Comment by Yaron10** [comment]
https://github.com/pnedev/compare-plugin/issues/280.

**Comment by jcstevensri** [comment]
Thanks @Yaron10. Curious why Notepad++ is insisting on disabling v2.0.1 and updating to v2.0.2 if the versions are incompatible. Perhaps this is an issue with Notepad++ more than with ComparePlugin.

**Comment by Yaron10** [comment]
@jcstevensri,

My pleasure.

> Perhaps this is an issue with Notepad++ more than with ComparePlugin.

👍
