### ISSUE TITLE
[Proposal] Which files to compare?

### ISSUE THREAD

**Issue by pnedev** [jsleroy/compare-plugin#13]
Hi guys,

I have a proposal about making the files to be compared more explicit.

Example of the current situation:

1) We have several files opened in N++
2) We are viewing one of them in N++ view 1
3) We are starting a compare action

At this point it is not quite clear for me as a user which files will get compared. The currently viewed one and the next? The previous?

So my suggestion is the following:

1) We have several files opened in N++
2) We are viewing one of them in N++ view 1
3) We move the second file to be compared to N++ view 2
4) We start compare and the currently active (viewed) files from N++ views 1 and 2 get compared

Does it make sense, what do you think?

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

I've just seen this post.
I'm now watching this repo (i.e. I've pressed the Watch button). :)

You're right. The scenario you've raised may be confusing.
But that behavior is controlled by NPP "Move to Other View" command which has some other issues as well (even with two files only).

1) When switching from "One View" to "Two Views", the active tab gets the bottom view (or right view) in some cases and the top view (or left) in others. 
2) In some cases, when returning from "Two Views" to "One View" - the previous order of the tabs is not restored.

It's certainly not random but still confusing.

I'd like to make sure I understand your suggestion correctly.
If more than two files are open, should we force the user to use "Move to Other View" before comparing?

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

Thanks for replying!
Yes, my suggestion is in case of more than two opened files to force the user to move one of the files to be compared to the other view before actually triggering the comparison operation.
If you have two views each with several files the active documents from the two views would be compared.

Does it make sense, what do you think?

PS: By the way, I just noticed that if I move one file to the other view before comparing when I close the compare results my files somewhat stay indented as if those are still in compare mode (the coloring is gone as it should be). Also those are not marked as 'dirty' (modified and needing saving) in Notepad++ but are actually not saved. My SVN doesn't detect changes. It appears those are just modified in the Scintilla buffers.

Thanks and Regards

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for getting involved. :)

I agree the current behavior is confusing.
Still - personally, I'm afraid it would slow and complicate my workflow.
How about a preference for that?
I wish we could get more feedback from other users. :)

Could you please upload the files you've compared and found the issue?
I'm not sure I understand the "stay indented" correctly. 

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

Sorry for replying that late.
I couldn't reproduce the "stay indented" issue so I guess it might have been something related to Wine (I'm working on Linux most of the time and using N++ under Wine).

You are right - in the future we could possibly add a configuration option for this behavior but for now it might confuse people even more, especially if they are used to working with the plugin.

Thanks for the feedback,
I'll write back when I play a bit with the code.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

No problem. :)
And thanks for clarifying the "stay indented" issue.

I think the "Move to Other View" command should be divided into two different commands:

1) Toggle One View/Two Views: when switching from One View to Two Views, the active tab *always* gets the top view and the tab next to it (needs some more elaboration) gets the bottom view.
Compare should use this command (check if One View now and toggle).

2) "Move to Other View": if we're in Two Views mode, move current to the other view.
(If only two files are open, switch the files' views).

IMO, it would make things much clearer; especially for Compare.
If it makes sense to you, I'll post a feature request.

Best regards.

**Comment by Yaron10** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1513

**Comment by pnedev** [comment]
Hi Yaron,

Again, sorry for the late reply.
Thanks for involving into this but I didn't quite grasp the idea, sorry.

Could you elaborate on why we would need point 1 (Toggle View)?

If I have opened several files in one view I don't find it confusing to move one of them to the other view using "Move to Other View" command. And the rest of the files remain in the first view.

The only thing that is not very handy is if you have several files in one view and several in the other. Then you would need to move files one by one to the other view if you want them in a single view.
I think this is where "Toggle One View/Two Views" command would be helpful - to simply unite all the files in a single view.

I wasn't quite familiar with the Compare plugin and I thought that when you have two files opened you simply run "Compare" and that's the only way to compare them actually.
I found out that what I'm proposing here is already existing Compare plugin function - if the files are in separate views and you run "Compare" action both files in the corresponding views get compared.

So ultimately my proposal here is pointless - it actually is already implemented :)

As to your point about which file gets into the first and witch - to the second view I perfectly agree with you.

Perhaps this is what needs to be modified in the plugin - when the compared files are in one view the currently active one should stay in this view and the other file needs to be moved to the other view.

Have I understood you correctly?

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

I hope you're doing well.
Don't worry about the late reply. :)

In Two-Views mode, the top (or left) view is ALWAYS 0, and the bottom view is ALWAYS 1.
However, in One-View mode, the current view can be 0 or 1.
(I think the easiest way to get the current view is by running `notepad.getCurrentView()` in PythonScript Console).

Let's try the following steps:
1) Start NPP with no files (Session etc.).
2) Open two files (One-View mode; current view is 0).
3) Press "Move to Other View"  (we switch to Tow-Views mode; current file is in view 1 (BOTTOM), and the second file is in view 0 (TOP)).
4) *Activate the file at top*, and press "Move to Other View" (we switch to One-View mode; current view is 1).
5) Press "Move to Other View"  (we switch to Tow-Views mode; current file is in view 0 (TOP), and the second file is in view 1 (BOTTOM)). 

So "Toggle One-View/Two-Views" should solve this problem: split the view and always keep the current file at top and the prev (?) file at bottom.
***
Replacing (in Compare.cpp)
```
	if(!IsWindowVisible(nppData._scintillaMainHandle) || !IsWindowVisible(nppData._scintillaSecondHandle))
	{
		skipAutoReset = true;
		SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);
		skipAutoReset = false;
		panelsOpened = true;
	}

```
with
```
	if(!IsWindowVisible(nppData._scintillaMainHandle) || !IsWindowVisible(nppData._scintillaSecondHandle))	// Yaron - One-View mode.
	{
		skipAutoReset = true;
		
		// Yaron - In One-View mode, the current view can be 0 or 1.
		// In Two-Views mode, the top (or left) view is ALWAYS 0, and the bottom view is ALWAYS 1.
		int currentView = SendMessage(nppData._nppHandle, NPPM_GETCURRENTVIEW, 0, 0);
		LRESULT bufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);
		TCHAR switchToFile[MAX_PATH];
		
		// Yaron - Store current file full path in switchToFile.
		SendMessage(nppData._nppHandle, NPPM_GETFULLPATHFROMBUFFERID, bufferID, (LPARAM)switchToFile);	
		
		// Yaron - IDM_VIEW_TAB_PREV; if the current view is 0, we want the prev file to be moved to the bottom; if the current view is 1, we still need to activate it and make sure it's compared to the current file. 
		SendMessage(nppData._nppHandle, WM_COMMAND, 44096, 0);
		
		if(currentView == 1)
		{
			bufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);
			SendMessage(nppData._nppHandle, NPPM_SWITCHTOFILE, 0, (LPARAM)switchToFile);		// Yaron - Switch back to current file.
			SendMessage(nppData._nppHandle, NPPM_GETFULLPATHFROMBUFFERID, bufferID, (LPARAM)switchToFile);		// Yaron - Store PREV file full path in switchToFile.
		}
			
		SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);		// Yaron - Current file is ALWAYS at top, and prev file is ALWAYS at bottom.
		SendMessage(nppData._nppHandle, NPPM_SWITCHTOFILE, 0, (LPARAM)switchToFile);		// Yaron - If the current view is 0, switch to current file at top; if the current view is 1, switch to prev file at bottom.
		
		if(currentView == 1)
			SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_SWITCHTO_OTHER_VIEW, 0);		// Yaron - Activate current file at top.
			
		skipAutoReset = false;
		panelsOpened = true;
	}

```
solves the issue in Compare. It also addresses the issue you have raised: if you have multiple files open, the current and prev (loop around) are compared.
The built DLL is attached. Could you please try it?

I'm sure there's a better way to implement this by using NPP internal code (instead of sending those messages).
If and when you find some free time, I'd highly appreciate it. :)
***
I didn't know you didn't know (it reminds me of Donald Rumsfeld's infamous sentence) about the option to compare in Two-Views mode. :)

Best regards.

[ComparePlugin.zip](https://github.com/jsleroy/compare-plugin/files/145719/ComparePlugin.zip)

**Comment by pnedev** [comment]
Hi, Yaron,

Thanks for explaining, now I see what you mean.
I tried the dll you sent me and it is working just fine :)

I agree with you that the Scintilla views should be handled better in Notepad++ itself so such switching between view 0 and 1, top, bottom (left, right) respectively is not noticeable by the user. For example, if I have two files open and I move both to other view then as you describe both will be in Sci1. Now if I move again one of them to other view it will go to Sci0 -> top or left which is a different behavior than the first move. So top (left) and bottom (right) views notation should be separated from Sci0 and Sci1. This will make Sci0 and Sci1 absolutely equivalent then.

It is good that you have created issues [1513](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1513), [1514](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1514) and [1515](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1515) but:
1) In my opinion [1513](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1513) should be changed as to add a single command that unites both views into one and the normal move to other view be handled appropriately. This would require some rework of the Sci views handling in Notepad++. 
2) As to [1515](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1515) - I think it might be difficult to implement and quite tricky also. For example, if you move some files to other view and then open some new files in both views then what would be the order? Various people will have various preferences I suppose... I actually would leave the current behavior as-is.

I'd also like to say that I really like the new icons you've made in the compare view - great job! Is there a merge request (Pull request) for those or they are already merge into the official repo?

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

Thanks for testing it. Great.

One question with your permission:
I couldn't find an NPP message to activate a file directly by its ID; I had to get the full path (by sending the ID) and use it (the path) later to activate the file.
Am I missing anything?

> 1) In my opinion 1513 should be changed as to add a single command that unites both views into one and the normal move to other view be handled appropriately. This would require some rework of the Sci views handling in Notepad++. 

There's a switch from One-View mode to Two-Views mode (and vice versa) , and a switch of a file from one view to the other when we're in Two-Views mode.
I'm not sure I understand your comment properly.
Anyway, I don't think Don is going to change anything soon. :)

> 2) As to 1515 - I think it might be difficult to implement and quite tricky also. For example, if you move some files to other view and then open some new files in both views then what would be the order? Various people will have various preferences I suppose... I actually would leave the current behavior as-is.

That's a good point.

> I'd also like to say that I really like the new icons you've made in the compare view - great job! Is there a merge request (Pull request) for those or they are already merge into the official repo?

I'm glad you like the icons. Thank you. 
I don't know how to change the XPM images background to transparent.
IMO, as long as this isn't fixed - those images should not be included in an official release. What do you think?
Actually, a better solution would be using BITMAPs instead of XPMs (we could then use 32bpp images).
Is that something you can easily change in the code? - It would be great.

I'm attaching the XPM files, and also the images with a transparent background.

Best regards.

[CompareIcons.zip](https://github.com/jsleroy/compare-plugin/files/147302/CompareIcons.zip)

**Comment by pnedev** [comment]
Hi Yaron,

> I couldn't find an NPP message to activate a file directly by its ID; I had to get the full path (by sending the ID) and use it (the path) later to activate the file.

Perhaps that should do:

`	#define NPPM_ACTIVATEDOC (NPPMSG + 28)`
`	//void NPPM_ACTIVATEDOC(int view, int index2Activate)`

> There's a switch from One-View mode to Two-Views mode (and vice versa) , and a switch of a file from one view to the other when we're in Two-Views mode.

Hm, I see there is a command in 'View' -> 'Focus on Another View' but I cannot find the switch from One-View mode to Two-Views mode. Can you tell me where I can find it?

My idea is to have a command that when in Two views mode gets you to One view by moving all the files to View0 - something like "merge views". I cannot find such command in the latest N++. Have I missed it?

And about the 'Move File to Other View': my thought was instead of introducing a new command in N++ (Toggle View) just to change the 'Move To...' command to behave properly by always moving to the right/bottom view if we were in single view before moving. This is actually to work-around the issue you mentioned earlier - that the views were 0 and 1 and not left - right (or top - bottom).

You are right though - Don won't be happy with such rework :)

> Actually, a better solution would be using BITMAPs instead of XPMs (we could then use 32bpp images).
Is that something you can easily change in the code? - It would be great.

I'd love to help you with that but unfortunately I don't have any experience with icons, bitmaps and XPMs. I just wanted to say that the new icons are great and I'd really like to see them in the official Compare plugin someday ;)
Thanks again!

BR,
Pavel

**Comment by Yaron10** [comment]
Hi Pavel,

Thanks for referring me to `NPPM_ACTIVATEDOC`. I appreciate it.

I'm looking for a way to get and set the active file *by using a single message* for each command.
For example:
`NPPM_GETFILENAME` and `NPPM_SWITCHTOFILE`.
The problem is that `NPPM_GETFILENAME` does not retrieve the full path which I need for `NPPM_SWITCHTOFILE`.
***
Regarding the views: I'm afraid I wasn't clear enough.
Currently the only way to switch from One-View mode to Two-Views mode is by using "Move to Other View".
But we agree there should be a way to switch from One-View mode to Two-Views mode *and have the current file in the top view*. IOW: split the view but do not move current to other view.
We also agree there should be an option to easily switch from Two-Views mode to One-View mode.
And a third option to move the current file to the other view if we're in Two-Views mode.
So how can we achieve those **three** actions with a single command? 
***
Regarding the icons:
I appreciate the good will. :) And thanks again for your kind words.

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

> The problem is that NPPM_GETFILENAME does not retrieve the full path which I need for NPPM_SWITCHTOFILE.

Well, I haven't used `NPPM_ACTIVATEDOC`myself but is seems to be usable for the purpose you need.

Otherwise, if you need to get the full file path you can use `NPPM_GETFULLPATHFROMBUFFERID` or `NPPM_GETFULLCURRENTPATH` istead of `NPPM_GETFILENAME`.

About the views:
You've done a great resume :) You are right, I agree with you. Somehow I missed the first use-case you described and was thinking of the next two. So finally it appears that two commands would suffice as you mentioned in your very first post - Toggle View and Move to View, correct?

Thanks for explaining.

BR,
Pavel

**Comment by Yaron10** [comment]
Hi Pavel,

Thank you so much for `NPPM_GETFULLCURRENTPATH`. I had missed it! :)
I've modified the code to:
```
	if(!IsWindowVisible(nppData._scintillaMainHandle) || !IsWindowVisible(nppData._scintillaSecondHandle))	// Yaron - One-View mode.
	{
		skipAutoReset = true;

		// Yaron - In One-View mode, the current view can be 0 or 1.
		// In Two-Views mode, the top (or left) view is ALWAYS 0, and the bottom view is ALWAYS 1.
		int currentView = SendMessage(nppData._nppHandle, NPPM_GETCURRENTVIEW, 0, 0);
		TCHAR currentFile[MAX_PATH], prevFile[MAX_PATH];

		// Yaron - Store current file full path.
		SendMessage(nppData._nppHandle, NPPM_GETFULLCURRENTPATH, 0, (LPARAM)currentFile);

		// Yaron - IDM_VIEW_TAB_PREV; if the current view is 0, we want the prev file to be moved to the bottom; if the current view is 1, we still need to activate it and make sure it's compared to the current file.
		SendMessage(nppData._nppHandle, WM_COMMAND, 44096, 0);

		if(currentView == 1)
		{
			SendMessage(nppData._nppHandle, NPPM_GETFULLCURRENTPATH, 0, (LPARAM)prevFile);		// Yaron - Store PREV file full path.
			SendMessage(nppData._nppHandle, NPPM_SWITCHTOFILE, 0, (LPARAM)currentFile);		// Yaron - Switch back to current file.
		}

		SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);		// Yaron - Current file is ALWAYS at top, and prev file is ALWAYS at bottom.

		if (currentView == 1)
			SendMessage(nppData._nppHandle, NPPM_SWITCHTOFILE, 0, (LPARAM)prevFile);		// Yaron - Possibly multiple files at bottom; activate prev.

		SendMessage(nppData._nppHandle, NPPM_SWITCHTOFILE, 0, (LPARAM)currentFile);		// Yaron - Activate current file at top.

		skipAutoReset = false;
		panelsOpened = true;
	}
```
[ComparePlugin.zip](https://github.com/jsleroy/compare-plugin/files/151683/ComparePlugin.zip)
***
As for the views:
Thank you.
Yes, it seems that Toggle View Mode and Move to Other View should be best.

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

Just modify for
`SendMessage(nppData._nppHandle, WM_COMMAND, 44096, 0);`
to
`SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_TAB_PREV, 0);`
for better readability.

Why don't you create a pull request then?

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much. I appreciate the mentoring. :)

`IDM_VIEW_TAB_PREV` is not included in Notepad_plus_msgs.h (ComparePlugin.v1.5.6.7\src\Common\Notepad_plus_msgs.h).
Should I add it to that file?
(In NPP repo it's in PowerEditor\src\menuCmdID.h).

Also, could you please confirm that my first PR here was done properly?

Best regards.

**Comment by pnedev** [comment]
Hi again, Yaron,

I didn't mean to offend you in any way, sorry if I did.
My purpose was not to "mentor" you either - I was just trying to give a feedback with the hope that it would be useful. But again - it is just my humble opinion.

> IDM_VIEW_TAB_PREV is not included in Notepad_plus_msgs.h 

Hm, I have missed that.
Personally I would then get the latest menuCmdID.h from Notepad++ project and use the IDM_VIEW_TAB_PREV define from there. It would make any future updates easier if for some reason N++ messages IDs change.

About your first PR - It solves the issue, yes, but it seems to me this only hides existing issue in the code that would manifest itself again in the future.
UFO had changed the value to 16 because he was trying to work around another issue - as he himself had written, if you compare 1 MB file against a smaller one (10 KB for example) then you would get an exception (this is with the original VARRAY value of 5).
Both are not acceptable for me but debugging this requires considerably more time than providing feedback in this thread. That's why I'm writing here so quickly and postponing to give you a reasonable feedback on the other issue.

BR,
Pavel

**Comment by pnedev** [comment]
Hi Yaron,

One more thing about
> I don't know how to change the XPM images background to transparent.

I assume in the XPMs you have sent me the background color is coded as '!' is that correct?
Have you tried using 'None' as '!'?

Here is part of the XPM:

`" 	c None",`
`"!	c #E4E4E4",`

Have you tried

`"!	c None"`

instead (if '!' is the background of course) ?

As I said I don't have any experience with icons, bitmaps, XPMs, etc. but I found an article in Wikipedia about XPM format and there is written that 'none' signifies transparent background.

Perhaps you've already tried that but anyway....

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

You are truly a kind gentleman.
You have much more experience than I do, and I really wanted to thank you for guiding/mentoring me.
I was not offended at all. On the contrary. :)
Allow me to thank you again for your invaluable feedback and help.

Do you mean adding menuCmdID.h to Compare? Should I put it in the Common folder?
***
Regarding the PR:
Now it's my turn to apologize.
I did not mean to rush you in investigating the issue. I was only referring to the general procedure of submitting PRs as it was my first one.

You have done a brilliant work. Thank you so much.
I'll add some more lines in the [PR thread](https://github.com/jsleroy/compare-plugin/pull/11).

Best regards.

**Comment by Yaron10** [comment]
Hi Pavel,

I posted before reading your last post.
Thanks for that too. :)

I was trying to modify the code in that direction.
I'll test it again later.

BR.

**Comment by Yaron10** [comment]
Hello again Pavel,

You're the best!
`"! c None"` has done it. The background IS transparent.
Thank you very much.

When you kindly reply to my question regarding menuCmdID.h, I'll submit a few PRs.

Best regards.

**Comment by Yaron10** [comment]
Hello again Pavel,

You're the best!
`"! c None"` has done it. The background IS transparent.
Thank you very much.

EDIT:
Claudia explained to me (in the forum) some time ago what XPM was. I didn't know '!' represented transparent.
Great work!

When you kindly reply to my question regarding menuCmdID.h, I'll submit a few PRs.

Best regards.

**Comment by Yaron10** [comment]
Hello Pavel,

With your permission, one more comment regarding XPM images:
The first XPM image I modified was the Bookmark in NPP (`static char * bookmark_xpm[] = {` in xpm_icons.h).
Not being able to make the background transparent, I didn't even try that with the Compare images.
Now I have returned to that image and it turns out to be more "stubborn". :)
Compare is built faster; so (for testing it) I have used the Bookmark image in Compare's icon_add_16.h.
If you have some free time to try "cracking" this one, I'd highly appreciate it.

[icon_add_16.zip](https://github.com/jsleroy/compare-plugin/files/157189/icon_add_16.zip)
***
When comparing new files (i.e. New 1, New 2 etc.), `NPPM_SWITCHTOFILE` does not work properly (the behavior is not consistent).
So, as you've kindly suggested, I had to use `NPPM_ACTIVATEDOC` which is slightly more complex.

```
	if(!IsWindowVisible(nppData._scintillaMainHandle) || !IsWindowVisible(nppData._scintillaSecondHandle))	// Yaron - One-View mode.
	{
		skipAutoReset = true;

		// Yaron - In One-View mode, the current view can be 0 or 1.
		// In Two-Views mode, the top (or left) view is ALWAYS 0, and the bottom view is ALWAYS 1.
		int currentView = SendMessage(nppData._nppHandle, NPPM_GETCURRENTVIEW, 0, 0);
		LRESULT bufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);

		// Yaron - IDM_VIEW_TAB_PREV; if the current view is 0, we want the prev file to be moved to the bottom; if the current view is 1, we still need to activate it and make sure it's compared to the current file.
		SendMessage(nppData._nppHandle, WM_COMMAND, 44096, 0);

		if(currentView == 1)
		{
			bufferID = SendMessage(nppData._nppHandle, NPPM_GETCURRENTBUFFERID, 0, 0);
			SendMessage(nppData._nppHandle, WM_COMMAND, 44095, 0);		// Yaron - IDM_VIEW_TAB_NEXT - Switch back to current file.
		}

		SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_GOTO_ANOTHER_VIEW, 0);		// Yaron - Current file is ALWAYS at top, and prev file is ALWAYS at bottom.
		
		activateBufferID(bufferID, currentView);		// Yaron - If the current view is 0, activate current file at top; if the current view is 1, activate prev file at bottom (possibly multiple files there).

		if (currentView == 1)
			SendMessage(nppData._nppHandle, WM_COMMAND, IDM_VIEW_SWITCHTO_OTHER_VIEW, 0);       // Yaron - Activate current file at top.

		skipAutoReset = false;
		panelsOpened = true;
	}
```
I have added the following function based on activateBufferID I've found in [PythonScript code](https://sourceforge.net/p/npppythonscript/code/ci/master/tree/PythonScript/src/NotepadPlusWrapper.cpp).

```
void activateBufferID(LRESULT bufferID, int view)
{
	LRESULT index = SendMessage(nppData._nppHandle, NPPM_GETPOSFROMBUFFERID, bufferID, view);
	index = index & 0x3FFFFFFF;
	
	SendMessage(nppData._nppHandle, NPPM_ACTIVATEDOC, view, index);
}
```
[ComparePlugin.zip](https://github.com/jsleroy/compare-plugin/files/157222/ComparePlugin.zip)

Thanks again for your kind help.

**Comment by pnedev** [comment]
Hi Yaron,

I'm glad things are working, good progress :)

It's late and I'll be brief:

1) About the _menuCmdID.h_ - Yes, you'll need to replace _Notepad_plus_rc.h_ in _Common_ sub-folder with _menuCmdID.h_. Just make sure _Compare.h_ includes the new file instead of _Notepad_plus_rc.h_.
I have actually done that together with a bunch of other changes and I'll soon publish those so you could wait a bit but you could also do it yourself. As you prefer..

2) About the new XPM - I'm not sure why it doesn't work but you could try removing the 'black' color entry - it is not used anywhere.
I've done it here:
[icon_add_16.zip](https://github.com/jsleroy/compare-plugin/files/157909/icon_add_16.zip)

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

The Bookmark XPM image is also transparent. I'm really impressed.

I've just seen you've forked the repo. :+1: 
That's more than I wished for. :) Looking forward to the upcoming changes.

I hope I'll start submitting some PRs tomorrow.

Thank you very much. I'm truly grateful.

Best regards.

**Comment by Yaron10** [comment]
Hi Pavel,

Some questions regarding Commits and PRs:

Should I submit 4 separate commits for the 4 modified images? 
I've read [this](https://help.github.com/articles/creating-a-pull-request/) article and I can't find the **Create pull request** button.
I assume I have to be in my fork and then create a PR. Correct?
How do I create *one* PR for the 4 modified images? 

Sorry to bother you with that. I'd appreciate your help.

BR.

**Comment by pnedev** [comment]
Hi Yaron,

I would suggest to create one branch in your fork with one commit containing all 4 modified images.
Then go to your fork, switch to the branch and you should see _Create pull request_.
Make sure that your branch is synchronized with the latest original master branch - this way you'll ensure no conflicts would arise.

Looking forward to see your fix ;)

BR,
Pavel

**Comment by Yaron10** [comment]
Hi Pavel,

I don't have the repo on my local machine.
I wouldn't like to bother you with these GitHub technical questions and, quite frankly, I find them rather boring.

Can I open an issue for my proposed changes and you would deal with the PRs?
I'd highly appreciate that.
If positive, should I open that issue in your fork?

Thank you very much.

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

In the beginning I thought I would simply help with fixing some issues.
However it appears that the plugin needs some serious modifications and rework. I started with that to see how it goes but to be honest I don't think my changes will ever be taken as PRs to the official repository because it will be extremely difficult to review them. Besides it appears only you and I are actually looking into the official repo so no one can actually review and merge.

That's why I am actually not planning to make any PRs but work on my own clone of the project. I'm also not quite sure I'll have the time and commitment to support the plugin in general (becoming a maintainer that is) so I don't promise anything. I'll try fixing as many issues as I can and see how it goes.

Having said that, there is no problem opening issues in my fork - I will directly merge your changes there but I will not make PRs for now.

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

I certainly understand your decision.
As I've mentioned before - your help, involvement and commitment are more than I wished for.
Allow me to sincerely thank you again.

Thanks also for ridding me of the PRs submissions. :)
I didn't have the time and peace of mind to look into it more seriously.

I'll open some issues in your fork (hopefully later in this week; I've had a busy day).

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

OK, great.
I'll stop writing in this thread then and later close the issue.

FYI: In my fork I have already updated the N++ API to version 6.9 - you can now use the N++ menu message IDs directly (_menuCmdID.h_ is available now)
I also have fixed the [crash issue](https://github.com/jsleroy/compare-plugin/issues/5) making [this fix](https://github.com/jsleroy/compare-plugin/pull/11) unnecessary (in my fork).

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

> I also have fixed the crash issue making this fix unnecessary (in my fork).

That's great. I'm really impressed.
I don't quite understand the changes you've made, so I can't compliment you on the quality of the code. :)

I assume you've decided to leave `#define VARRAY_INIT_SIZE 16`.
What about the loops in Compare.cpp?
```
   for (int i = 0; i < doc1Changed; i++)
    {
        doc1Changes[i] = {};
    }
```
***

> you can now use the N++ menu message IDs directly (menuCmdID.h is available now)

I already changed that in my code when you first suggested it.
Your modifications are much more comprehensive than just menuCmdID.h. Thank you!
***
I was about to open some issues in your fork.
I think you need to enable "Issues" in Settings.
So one more reply here. :)

Best regards.

**Comment by pnedev** [comment]
Hi Yaron,

Of course, you are right, the "Issues" are enabled now :)

I have reworked the variable array implementation so `VARRAY_INIT_SIZE` is not used anymore.
There are still problems though when comparing very big with very small files (UFO's crash scenario) - the memory allocation fails. I hope it'll get better when I optimize code further but I'm not certain of this.

The loops are no problem, they can be left as they are for now.

BR,
Pavel

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for enabling "Issues".

And thanks again for your great work. Interesting.
I'll download your fork once you've merged my proposed changes.

Best regards.

**Comment by pnedev** [comment]
This issue is not relevant anymore.
Thanks everyone.
