### ISSUE TITLE
Black Screen when compare exceeds 16384 lines

### ISSUE THREAD

**Issue by shadinaif** [jsleroy/compare-plugin#14]
Hello,

It is a great tool. But I am facing a problem with files containing more than 16384 lines (2^14). The screen gets black, I have to press Alt+F4 to close notepad++ to retrieve the desktop

Do you have a solution without splitting the file into many?

Best Regards,

**Comment by Yaron10** [comment]
Hello shadinaif,

I've read some reports about the comparing process taking a long time with large files.
Have you tried waiting for some 3-4 minutes?
It's not a practical solution, but it can be interesting.

Best regards.

**Comment by shadinaif** [comment]
Hello @Yaron10 ,

Unfourtunatly; this is not the case. I tried it on Windows XP 32 and went fine. My System (having the problem) is Windows 7 Pro 64.

What I am doing is:
1. create an empty text file
2. Fill the file with only one letter per line, and repeat it for 16383 lines
3. Save it, it should be as small as 48 KBytes
4. Create a copy of the file, and modify one line of it (so they wouldn't be identical)
5. Compare them, you will find no problem now
6. Open one of the two files and add a single line (limit is now reached 16384)
7. NOW MAKE SURE THAT NOTEPAD++ WINDOW IS MAXIMIZED
8. Compare them, now the screen goes black. Not Notepad ++ is black, no, the whole desktop
9. Press Alt-F4 to Close Notepad ++. The desktop is now is available again. It is like Notepad ++ was locking the GDI
11. Open the same two files with Notepad++
12. SWITCH NOTEPAD++ WINDOW TO CASCADE
13. Compare them, Now the screen blinks black then restored, The NAV Bar is empty, I believe it is the source of the problem

I am trying this using the latest version 6.9 . 

If you did not face the problem, then please tell me about it so I would look into my GDI and display adapter definition files :(

Thank you for your reply

Best Regards,

**Comment by Yaron10** [comment]
Hello shadinaif,

Thank you for clarifying the issue.

My OS is Win 7 32-bit.
Could you please upload the files?

May I ask which Compare version you're using?
Can you try [this](https://github.com/jsleroy/compare-plugin/files/99845/ComparePlugin.v1.5.6.7.NewImages.NoDefault.bin.zip) build?

Best regards.

**Comment by shadinaif** [comment]
Sorry @Yaron10 for the late answer,

I have tried your build and it is working fine :+1: 

I was trying the latest version from the download manager ! Is it a settings issue?

Best Regards,

**Comment by Yaron10** [comment]
Hello shadinaif,

I'm glad it works properly.

> Is it a settings issue?

The Download Manager doesn't always provide the latest versions.
If you're referring to the relevant difference between the versions: I don't know. :)

Best regards.

**Comment by shadinaif** [comment]
Thank you very much dear @Yaron10 ,

I am setting this issue as closed :+1:

**Comment by Yaron10** [comment]
My pleasure. :)
