### ISSUE TITLE
Compare colorization is not cleared properly

### ISSUE THREAD

**Issue by pnedev** [jsleroy/compare-plugin#16]
1) Open 3 files in N++
2) Trigger 'compare'
3) Go to the view with the two files. Let's call the file that is compared and colorized 'fileA'. Switch to the other file
4) Clear compare results
5) Switch again to 'fileA'. It is still colorized as if being compared.

BR,
Pavel

**Comment by Yaron10** [comment]
Hi Pavel,

That's a good catch. :) Thank you.

Best regards.
