### ISSUE TITLE
Clear Results doesn't restore syntax highlights

### ISSUE THREAD

**Issue by CTimmerman** [jsleroy/compare-plugin#21]
When returning from a comparison in Notepad++ 6.9.2 with Compare plugin 1.5.6, I have to insert a newline at the top of the code to get syntax highlighting back.

**Comment by pnedev** [comment]
Compare plugin 1.5.6 is rather old.
I'll release v2.0.0 soon that fixes many problems.
If you can compile the plugin yourself and can't wait the release you can use the latest source code snapshot.
