### ISSUE TITLE
Notepad++ v7 64bit support 

### ISSUE THREAD

**Issue by narutards** [jsleroy/compare-plugin#47]
I've been using Notepad++ for an eternity and heavily relied on the Compare plugin for it to easily diff source code.
With the release of the Notepad++ version 7 in 64bit I naturally switched to that .. only to find out that the Compare plugin is not yet compatible.
Any chance to get a working 64bit binary build of the plugin soon-ish?

**Comment by pnedev** [comment]
Yes, that will be ready soon.

**Comment by jaegerschnitzel** [comment]
That would be great!

**Comment by pnedev** [comment]
CP x64 is ready and completely usable.
You need to either compile it yourself for x64 or you can take it from
https://ci.appveyor.com/api/buildjobs/l6levanxkyh3f9la/artifacts/ComparePlugin.X64.Release%20Unicode.v120_xp.dll
You will also need to replace the _git2.dll_ and _sqlite3.dll_ files in your _Npp_Install_Path\plugins\ComparePlugin\_ folder with their 64bit versions from
https://github.com/jsleroy/compare-plugin/tree/master/libs/x64.

If you find any issue please report it here, thanks.
