### ISSUE TITLE
Compare does not work with 64-bit Notepad++

### ISSUE THREAD

**Issue by fishboy2e** [jsleroy/compare-plugin#56]
When I tried to load ComparePlugin.dll into the plugins directory and start Notepad++ I received the following error: 
![compareplugin dll](https://cloud.githubusercontent.com/assets/24319030/20838692/8335b934-b85e-11e6-9877-aa3e5ec7f3a9.jpg)

is there a plan to port this for 64-bit Notepad++ and what is the timeframe if so?

thanks for your GREAT Work!

**Comment by pnedev** [comment]
Please look at this post:
https://github.com/pnedev/compare-plugin/issues/101

If you still have any trouble just write back.

BR
