### ISSUE TITLE
Plugin not supported in notepad++

### ISSUE THREAD

**Issue by xallindrome-dev** [jsleroy/compare-plugin#59]
I'm getting the following error: "This plugin is not compatible with current version of notepad++." It might be result of changing from Notepad 6 to 7. What can I do to remedy this error? I have installed the dll in the correct plugin folder.

**Comment by pnedev** [comment]
Perhaps you have 64-bit Notepad++ but the plugin dll you have is 32-bit (or vice versa).
Open Notepad++ and go to menu _?_ -> _About Notepad++_ to check your Notepad++ version (64 or 32 bit).
Go to https://github.com/pnedev/compare-plugin/releases/tag/v2.0.0 and download ComparePlugin_v2.0.0_X64.zip if your Notepad++ is 64-bit or ComparePlugin_v2.0.0_x86.zip in case Notepad++ is 32-bit.

BR
