### ISSUE TITLE
Align compare tab when using multiline tab mode

### ISSUE THREAD

**Issue by tithom** [jsleroy/compare-plugin#60]
Hello,
I have often a lot of tabs opened, so I enable the notepad++ option "Tab Bar / Multi-line" in the General preferences menu.
Since the tabs appears only on the left side, this create a shift between the left and the right side, making the diff harder to read. See the image bellow.

The right side should be shift as well as the left side to avoid this problematic.

![pbtabbar_nppcompare](https://cloud.githubusercontent.com/assets/308400/22974934/e9c96284-f384-11e6-83ae-1bf91ed04b47.png)

**Comment by pnedev** [comment]
Hello,

Yes, that was already reported here https://github.com/pnedev/compare-plugin/issues/105 and fixed after https://github.com/pnedev/compare-plugin/commit/bf46ed1858a75c19057f93aaaccd6c66b6b1c319.

The corresponding binaries are

- x64:  https://ci.appveyor.com/api/buildjobs/76labjggl914ffdt/artifacts/ComparePlugin.dll
- x86:  https://ci.appveyor.com/api/buildjobs/p5vsue8bqv0u4dvw/artifacts/ComparePlugin.dll

I won't be actively supporting / answering issues here. If you need help please write on my Compare Plugin clone page - https://github.com/pnedev/compare-plugin.

BR

**Comment by tithom** [comment]
Oh right thank you, didn't see the new version is continued on a fork. The source/homepage on the Plugin manager links to this page. Perfect
