### ISSUE TITLE
Flickering, black blocks, broken scrolling, lines misaligned

### ISSUE THREAD

**Issue by CrescentEclipse** [jsleroy/compare-plugin#61]
Hi, I am new here and only registered at github, because I like and use the compare plugin a lot and now getting some serious errors.

Unfortunately this plugin is unusable in its current state. I never had any problems with the previous versions and I liked to use it a lot for work and private purposes. Now it simply doesn't work anymore.

I can only scroll down, regardless of the mouse wheel direction. When I scoll it flickers heavily and both sides are not in sync. Additionally it shows black blocks and behaves randomly. Please see the attachment for an example. Thank you :)

![npp compare bug](https://cloud.githubusercontent.com/assets/25794343/22976238/3d26b968-f38a-11e6-8810-3e535ed0a485.png)

Notepadd++ v5.9.5
Compare v2.0

**Comment by pnedev** [comment]
Hello,

Your N++ is antique. Please update your Notepad++ to its latest version 
(currently https://notepad-plus-plus.org/download/v7.3.2.html) and try again.
Or you can go back to your previous ComparePlugin version (1.5.something).

BR

**Comment by pnedev** [comment]
@CrescentEclipse ,
Any update on this?

**Comment by CrescentEclipse** [comment]
Sry, I was busy lately.
It works fine now, but the comparison could be a bit more precise.

**Comment by pnedev** [comment]
OK.

> but the comparison could be a bit more precise.

What do you mean?

**Comment by Yaron10** [comment]
@CrescentEclipse,

@pnedev has fixed tens of bugs and introduced many great new features in v2.
CP users should be very grateful for his amazing work.

Can you be more *precise* in "but the comparison could be a bit more precise."?

**Comment by CrescentEclipse** [comment]
I totally appreciate his work for this plugin, but I never recognized any bugs with the old version. Additionally both versions produce similar results. I only was able to compared them very little by now due to the lack of time, but I maybe should intensify this.

What I am unhappy about is the move detection. I have to admit, they both do the same mistakes, but the old one is a bit more accurate. I don't know how to explain this. I will try with a quick stupid example:

-|v1 Old File|-|v1 New File|-|-|v2 Old File|-|v2 New File
-|-|-|-|-|-|-|-|-
Moved|Start|-|-|-|-|-|Moved|Hello
Moved|End|-|-|-|-|-|Added|End
-|Hello|-|Hello|-|-|Start|-|Start
-|-|Moved|End|-|Removed|End|-|-
-|-|Moved|Start|-|Moved|Hello|-|-

I know, this is not the best example, but If you have code blocks and some changes here and there, then the compare plugin does not detect the moves and just assumes something was added and/or removed. The lines are misaligned and you can't compare the changes properly. This is a problem with both versions, no offence.

**Comment by pnedev** [comment]
Hello @Yaron10 ,

Thanks.

Hello @CrescentEclipse ,

That is a problem with v2.0 that Yaron already found recently (please look at https://github.com/pnedev/compare-plugin/issues/113).
The issue is fixed - you can get the x86 binary here:
https://ci.appveyor.com/api/buildjobs/c54bu3uivybjri6x/artifacts/ComparePlugin.dll

Please have in mind that this is a pre-release development version and has some extra features/fixes.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you.

Hello @CrescentEclipse ,

If you have any other suggestions, please join the discussion in https://github.com/pnedev/compare-plugin/issues/113.

Thank you.
BR
