### ISSUE TITLE
v2.0 Fails Plugin Manager integrity check ("It has not been possible to validate the integrity of 'ComparePlugin.dll'")

### ISSUE THREAD

**Issue by AsaRossoff** [jsleroy/compare-plugin#62]
Plugin Manager gives the error `It has not been possible to validate the integrity of 'ComparePlugin.dll' needed to install or update a plugin.  Do you want to copy this file anyway (not recommended)?`

If one proceeds anyway, the same error is also given for:
* git2.dll
* sqlite3.dll

**Comment by Yaron10** [comment]
Hello AsaRossoff,

If you're using NPP 32-bit, update your Plugin Manager to v1.4.3 and then install Compare Plugin v2.
If you're using NPP 64-bit, download [Compare Plugin v2 64-bit](https://github.com/pnedev/compare-plugin/releases/tag/v2.0.0) and install it manually (i.e. unzip the file in your plugins folder).

Best regards.

**Comment by AsaRossoff** [comment]
I am experiencing this issue with Plugin Manager 1.4.3 in 32-bit Notepad++ 7.3.2 already/

Thanks :)

**Comment by Yaron10** [comment]
Hello AsaRossoff,

You're welcome.

I removed my Compare Plugin, reinstalled it via the Plugin Manager and did not get that message.
@pnedev might have another idea.

Anyway, you can remove your Compare Plugin (including the ComparePlugin folder) and install it manually.

Best regards.

**Comment by Yaron10** [comment]
Hello again,

Plugin Manager -> Settings: if you check "Use development plugin list" that message does not show up.

Best regards.

**Comment by AsaRossoff** [comment]
Hi Yaron10,
Yep, that bypasses the message.

It seems like it would be desirable for the plugin to either validate without that option, or only be listed on the development plugin list, though...

**Comment by Yaron10** [comment]
Hello AsaRossoff,

> It seems like it would be desirable for the plugin to either validate without that option...

You're absolutely right, but I think it's up to the Plugin Manager update frequency. 

Best regards.

**Comment by AsaRossoff** [comment]
Egh, I'll leave this open in case something should/could be addressed.  I don't see this issue with most plugins.  Some plugins have newer versions that only appear when the Development Plugin List is enabled, but they also have a version on the standard list that passes validation and installs...

**Comment by pnedev** [comment]
Hello @AsaRossoff and @Yaron10 ,

@Yaron10 , thanks for responding and helping with this.

@AsaRossoff ,

Unfortunately nothing can be done at the moment. The PluginManager list needs to be updated and when that happens the issue will be solved.

> It seems like it would be desirable for the plugin to either validate without that option, or only be listed on the development plugin list, though...

That is currently not possible. The 'development' PluginManager option gets the new plugins' list with the new versions and validation rules. Without that option the old list is gotten which is not properly filled (partially it's my mistake when releasing the new plugin version) but the plugin is already released (the previous versions) and thus the name is not changed so it will appear in both lists regardless the validation issues.

BR

**Comment by pnedev** [comment]
FYI: https://github.com/bruderstein/nppPluginManager/issues/41

**Comment by Yaron10** [comment]
Hello Pavel,

I'm glad I could save you some time and reply to @AsaRossoff earlier.
And thank you for the explanation.

BR

**Comment by AsaRossoff** [comment]
@pnedev - thanks; glad to hear you're aware of the issue.  That was my goal -- to make sure  you were aware of the issue.  Thanks also for your Compare development, a very valuable addition to NPP!
Thanks again for the kind support, too, Yaron10!

**Comment by pnedev** [comment]
@AsaRossoff ,
You are welcome.
BR

**Comment by Yaron10** [comment]
Hello AsaRossoff,

> That was my goal -- to make sure you were aware of the issue.

Thank you for reporting the issue to Pavel.

> Thanks again for the kind support, too,

It was pleasure.  :)

BR

**Comment by khashayarnazari** [comment]
> Plugin Manager gives the error `It has not been possible to validate the integrity of 'ComparePlugin.dll' needed to install or update a plugin. Do you want to copy this file anyway (not recommended)?`
> 
> If one proceeds anyway, the same error is also given for:
> 
> * git2.dll
> * sqlite3.dll
