### ISSUE TITLE
[Enhancement] Can we get some documentation?

### ISSUE THREAD

**Issue by LynnMaISD** [jsleroy/compare-plugin#68]
I realize that this is a super simple and mostly self-explanatory, but there is one thing that I cant find, regarding the symbolism (in the side column when doing a diff, the +- are obvious but what is the orange what looks like an equals sign with a line down the center of it?). 

Maybe if someone was bored they could add single HTML page that describes the plugin, and put a link to it hosted somewhere in the about box in the plugin?

**Comment by Yaron10** [comment]
Hello @LynnMaISD,

![image](https://cloud.githubusercontent.com/assets/10229320/23635918/12ddd5d2-02db-11e7-8776-91a82c4343db.png) : Two lines and an exclamation mark over them. 
Meaning: the lines have been modified (not equal).

Boredom or other reasons, a short User-Guide will be added to the next version.

Please submit any other questions and requests in Pavel Nedev's [repo](https://github.com/pnedev/compare-plugin).
Thanks.

Best regards.

**Comment by pnedev** [comment]
Hello @LynnMaISD ,

Yaron has answered fully your question, please write back if you need any further assistance.
Thank you.

@Yaron10 ,

Thank you for supporting @LynnMaISD and for taking care of the User Guide for the next CP release. Much appreciated :+1: 

BR
