### ISSUE TITLE
NavBar issues with large files

### ISSUE THREAD

**Issue by Ravenheart** [jsleroy/compare-plugin#72]
Greetings, 

when comparing large text files the NavBar breaks and starts display random parts of the screen instead of the diff. First noticed it when comparing files with different encodings, but it also occurs when comparing same encodings.

Attached is a zip with 3 large files that when compared break the NavBar. Try comparing utf8.txt vs w1251.txt and also utf8.txt vs utf8-modified.txt.
[Git.zip](https://github.com/jsleroy/compare-plugin/files/918930/Git.zip)

**Comment by pnedev** [comment]
Hello,

What version of CP are you using? What is your Notepad++ version? What is your operating system?
I couldn't reproduce the issue with N++ 7.3.3, CP 2.0 on Win7 and the files you have attached.

BR

**Comment by pnedev** [comment]
Hello @Ravenheart ,

Any update on this?
Thanks.

BR

**Comment by Ravenheart** [comment]
Sorry about the delay, missed the previous notification, I was on 1.5.6 where the bug occurred, gonna try it out tomorrow morning on 2.0.

**Comment by Ravenheart** [comment]
Works fine in 2.0 thanks.
