### ISSUE TITLE
Instruction for the plugin

### ISSUE THREAD

**Issue by Sibojang9** [jsleroy/compare-plugin#75]
I am a first-time user of this plugin. There are many options of the plugin.
Like  "set as first to compare", "compare", "clear active compare". some are self-explanatory. some are not.
Is there any instruction available to explain the use of them?
Thank you.

**Comment by Yaron10** [comment]
Hello @sibojan,

The next Compare Plugin version should include a short user-guide.
Please have a look at https://github.com/pnedev/compare-plugin/issues/116.

NOTE: some of the info in the **Symbols** section is inaccurate.

If you have a specific question, please open an issue in Pavel Nedev's [repo](https://github.com/pnedev/compare-plugin) and I'll be glad to help.

Best regards.

**Comment by Sibojang9** [comment]
Thanks.
