### ISSUE TITLE
Close plugin

### ISSUE THREAD

**Issue by razvancoding93** [jsleroy/compare-plugin#77]
Can't stop comparison plugin.

**Comment by pnedev** [comment]
I don't understand your issue, sorry.

**Comment by razvancoding93** [comment]
I tried again to compare and "Plugins->Compare->Clear All Compares" and now worked fine, yesterday when I pressed "Clear All Compares" nothing happened, and I had to close file from right side manually to close comparision. If I'll get in this situation again I'll record and send you. Thank you.

**Comment by pnedev** [comment]
OK, write again if that happens.
