### ISSUE TITLE
Feature Request: Restore old shortcut or make it customizable

### ISSUE THREAD

**Issue by martinstephenbanks** [jsleroy/compare-plugin#79]
I use the Compare tool religiously to compare scripts from my DEV environment to my PROD environment and I have become extremely programmed to the Alt + D shortcut. I just updated the plugin because the Change Highlight was no longer working and, whilst it did successfully fix that issue, it has now got a new shortcut key combination of 3 keys (Ctrl + Alt + C).

It would be very advantageous if this change could be reverted or if you could make a way that we can choose our Shortcut for our personal installation.

Other than that tiny detail, the plugin is AWESOME!! Thanks very much!

Many thanks,
Martin Banks

**Comment by Yaron10** [comment]
Hello Martin,

https://github.com/jsleroy/compare-plugin/issues/63#issuecomment-281835024

Best regards.
