### ISSUE TITLE
When I hold Alt-key and drag my mouse, a prompt box pops up

### ISSUE THREAD

**Issue by MyYellowBlanket** [jsleroy/compare-plugin#83]
in Notepad++ v7.4.2 (32-bit)

![image](https://user-images.githubusercontent.com/11293327/29740464-e3df8686-8a89-11e7-85fe-6575f1dbee28.png)

I only intend to do some vertical editing ( Column Mode Editing ).

**Comment by MyYellowBlanket** [comment]
Looks like it has the same effect as Ctrl + Alt + C when I hold Alt-key and drag my mouse.

**Comment by Yaron10** [comment]
I can not reproduce that.

Can you check the Shortcut Mapper for any conflicts?
If you don't find any, please test it with a [portable NPP](https://notepad-plus-plus.org/download/v7.5.html) (i.e. download the ZIP package and only add Compare Plugin).

Please post any other issues/requests in [Pavel Nedev's repo](https://github.com/pnedev/compare-plugin).

**Comment by MyYellowBlanket** [comment]
Thank you. 

I now find out what caused the problem. It's the "Selected Translation 划词翻译" of YoudaoDict, a commonly used English-Chinese dictionary software.

**Comment by Yaron10** [comment]
You're welcome.
I'm glad you've found the cause.

Best regards.

**Comment by pnedev** [comment]
Hello @Yaron10 ,

Nice to 'hear' from you :)
I hope you are doing well.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I'm fine. Thank you.
I hope you are also doing well and enjoying the work on CP (for which I'm grateful). :)

Best regards.
