### ISSUE TITLE
Aligning Matches

### ISSUE THREAD

**Issue by renatoab** [jsleroy/compare-plugin#85]
![compare](https://user-images.githubusercontent.com/1058654/33072834-b6da95fe-ce9f-11e7-98f6-a851b04384cc.png)

Hi,

The Compare plugin is very useful for me when i need to test newer versions of a software I work with, since i need to compare several reports generated from different versions.
The ability to recognize small differences in values was a good improvement.
But i still see some situations that could be improved.
Sometimes some blocks of the files have differences in most of the lines. The older versions of the plugin didn't recognize the blocks and refused to align them. The version 2.0.0 works better, it seems to know that those blocks are the same, but there's some issue in the alignment. When I click in some part of a file, the other scrolls automatically, but they don't get aligned properly, and sometimes it breaks the alignment. On older versions, the matched lines get always aligned, but in 2.0.0 sometimes they don't. Since i sometimes need to compare hundreds of files with thousands of lines, it would be a huge improvement if they align automatically as well as older versions did.
There are other sugestions I would like to make. When comparing lines with numbers, it seems to have a tolerance, and seems that decimal numbers are not recognized. The option to customize that tolerance would be very interesting, and the ability to recognize decimal numbers would also help.

Thank you,

Renato

**Comment by pnedev** [comment]
Hello Renato,

I am the developer of v2.0 but since I did a lot of changes that diverged from the original project please visit my compare project clone (https://github.com/pnedev/compare-plugin).
Feel free to report any issues / suggestions there.

BR
