### ISSUE TITLE
Windows Ready Version

### ISSUE THREAD

**Issue by mltco78dhs** [jsleroy/compare-plugin#86]
How difficult is it to simply offer a Windows-ready version of this instead of forcing potential users to download tools to "make" the thing?

Honestly, Linux developers give me gas. 30 years in IT and I never met one who didn't have an attitude about every other operating system, the morons who use them, and the general lack of intelligence of anyone who didn't use their own favorite build of Linux.

The overreaching philosophy on everything seems to be "If it was hard to write, it should be hard to use."

Yes, I get it. You're clever. Now will you please stop screwing around and finish the job instead of trying to impress the rest of us about just how clever you are that you'd rather download source code and compile yourself than deign to use a precompiled dll?

Not everyone who wants to use this wants to fiddle around with this nonsense.

**Comment by pnedev** [comment]
If you are talking about v2.0 I did the development but since I do not have the rights to setup an automated build for jsleroy's compare project I only updated the source here. The binary is at my project's clone:
https://github.com/pnedev/compare-plugin/releases/tag/v2.0.0

BR

**Comment by Yaron10** [comment]
@mltco78dhs,

Pavel Nedev is indeed clever and many CP users are grateful for his remarkable work.
He was even kind enough to reply to your rude and incoherent post.
