### ISSUE TITLE
FeatureRequest: folder compare

### ISSUE THREAD

**Issue by ghost** [jsleroy/compare-plugin#88]
I am working locally on a site housed on a shared drive with others in the office. Since several of us were working on similar files I made a copy of the site and worked on that one so I wouldn't step on any one elses changes. Now I have the problem of figuring out where my changes were made and applying them back into the main site.

Compare is ideal for this when comparing one of the current files and one I had worked on to see where my changes are. With a folder compare I'm envisioning a list of files that are different in a folder maybe with light details about each side before you jump into one of the pairs. No difference. Extra content on one side to the other, I know that's probably a file someone else was working on and added a new function. Different changes on both files, OK that's what I'm looking for and then I could jump in and compare the two and incorporate my changes.

Maybe something like that already exists out there and I'm just not aware of it?

**Comment by pnedev** [comment]
Hello @bimagecircle ,

Currently it is not possible to compare whole folders with the plugin.
You'll need to use dedicated external compare program for that (BeyondCompare, WinMerge, etc.).
