### ISSUE TITLE
Allow user to change shortcut keys

### ISSUE THREAD

**Issue by serg3y** [jsleroy/compare-plugin#89]
Ctrl+Alt+C and Ctr+Alt+Shift+X is just too much for something i use so much...

I want to go back to the old keys or set something simpler for myself like:
Ctrl+Space and Ctrl+Shift+Space

Please

**Comment by pnedev** [comment]
Well, do it :)

Open Notepad++ -> _Settings_ -> _Shortcut Mapper_ -> _Plugin Commands_. Find the Compare plugin commands and change the corresponding shortcuts.
