### ISSUE TITLE
Row click function

### ISSUE THREAD

**Issue by hyperion0x** [jsleroy/compare-plugin#90]
Hi, 

i have two tabulator tables and i would like to see the selected rows (one or many) into the second table when i click on them on the first table.
the first table show rows with 10 columns. I'm tryng to get the result with the following code but when i click but i have this error:

![error1](https://user-images.githubusercontent.com/39456618/40888495-3766e168-6758-11e8-833c-b3f053704211.PNG)

`rowClick:function(e, id, data, row)
	{ 
		//load data	
		var idbo=row.getData().IDBO;
		
		$("#mytable2").tabulator("setData", [{IDBO:row.getData().IDBO,}]); //make ajax request with advanced config options
	},`

IDBO is one of the 10 columns composing a selected row in the first table. 
1. Is it the sintax correct?
2.Am i obliged to specify all 10 columns that normally compose the first selected row?

thanks a lot,

**Comment by hyperion0x** [comment]
hi nobody cant help on this subject?

**Comment by Yaron10** [comment]
Hello @hyperion0x,

Is this related to Compare Plugin?

**Comment by hyperion0x** [comment]
sorry wrong topic. Didnt see...i ll close it immediately.
